name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Obtener el código
        uses: actions/checkout@v3

      - name: Validar que los archivos existen
        run: |
          ls -la
          echo "Pipeline funcionando correctamente"
      - name: Validar HTML
        run: |
          echo "Validando HTML..."
          if grep -q "<html>" index.html; then
            echo "HTML válido"
          else
            echo "HTML inválido"
            exit 1
          fi
